version: '3'
services:
    kafka:
      image: wurstmeister/kafka
      container_name: kafka
      ports:
        - "9092:9092"
      environment:
        - KAFKA_ADVERTISED_HOST_NAME=192.168.99.100
        - KAFKA_ADVERTISED_PORT=9092
        - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      depends_on:
        - zookeeper
    zookeeper:
      image: wurstmeister/zookeeper
      container_name: zookeeper
      ports:
        - "2181:2181"
      environment:
        - KAFKA_ADVERTISED_HOST_NAME=zookeeper
#    fluxoftweet:
#      container_name: fluxoftweet
#      image: fluxoftweet:latest
#      ports:
#        - "9001:9001"
#        - "9098:9098"
#      depends_on:
#        - kafka
#        - zookeeper
